### ISSUE TITLE
Questions about datasets

### ISSUE THREAD

**Issue by liu-yuyun** [Mithunjha/EarEEG_KnowledgeDistillation#1]
Hello author, how to download the dataset in this code of yours? Or can you share the dataset you used in this paper?

**Comment by Mithunjha** [comment]
Hi, our work was based on the dataset from the paper : https://biomedical-engineering-online.biomedcentral.com/articles/10.1186/s12938-017-0400-5. I would recommend that you contact the authors of that paper directly to inquire about accessing the dataset.
