### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by wenxin-CODE** [Mithunjha/EarEEG_KnowledgeDistillation#2]
is:open label:question can you tell men how to download the data which is used in <Automatic sleep staging using ear-EEG>

**Comment by Mithunjha** [comment]
Hi, our work was based on the dataset from the paper: https://biomedical-engineering-online.biomedcentral.com/articles/10.1186/s12938-017-0400-5. I recommend contacting the authors of that paper directly to inquire about accessing the dataset.

**Comment by wenxin-CODE** [comment]
Hello, I have asked the author for the data. But he said that the data had a new version. I am not sure that it is same as what you used before. And there is not rejected.h5 file. How can I work it.&nbsp;The new data is shown below







惟伊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mithunjha/EarEEG_KnowledgeDistillation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月6日(星期六) 中午12:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mithunjha/EarEEG_KnowledgeDistillation] dataset (Issue #2)





 
Hi, our work was based on the dataset from the paper: https://biomedical-engineering-online.biomedcentral.com/articles/10.1186/s12938-017-0400-5. I recommend contacting the authors of that paper directly to inquire about accessing the dataset.
